### ISSUE TITLE
importing Microsoft.ActiveDirectory.Management.dll doesn't really work 

### ISSUE THREAD

**Issue by cpu0x00** [wsummerhill/CobaltStrike_RedTeam_CheatSheet#1]
Hello, 

importing Microsoft.ActiveDirectory.Management.dll from within the beacon doesn't really work
do you have any idea or does it work with you and its a problem on my end??

**Comment by wsummerhill** [comment]
If you import it just in your own PowerShell session (not Beacon) does it work for you? This worked in the past but its an old technique so possible it doesn't work anymore. 
I will have to re-test and update the blog accordingly, thanks!

**Comment by cpu0x00** [comment]
@wsummerhill in a normal powershell session yes indeed it works, but it in beacon it doesn't work it spits out some bytes and dies , my test was on cobaltstrike 4.8, i tried a bunch of different ways to get it to work with beacon non works 

sorry for the massively late reply.

**Comment by wsummerhill** [comment]
You're right, I will remove this from the techniques.

There might be another manual way to do it in Cobalt Strike if you have the RSAT module installed and DLL on disk which isn't as great but still possible. Run it inline in a single command, its just limited by the command line length and requires RSAT:
(Note that I haven't tested this as I dont have a server with RSAT right now)

`powershell import-module C:\path\to\RSAT\location\Microsoft.ActiveDirectory.Management.dll; get-command Get-AD*`

**Comment by cpu0x00** [comment]
@wsummerhill
 
solved it !

made a little modification to Import-ActiveDirectory.ps1 originally published here https://github.com/samratashok/ADModule/ to call the Import-ActiveDirectory function once its loaded in the beacon
 
so now with the normal powershell-import: 
`powershell-import /path/to/Import-ActiveDirectory.ps1`
`powershell Get-Command Get-AD*`

*all i did is adding "Import-ActiveDirectory" at the end of the file to make it reflectively load the bytes of the dll once imported*

**Comment by wsummerhill** [comment]
Great to hear, well done! Closing the issue.
